# Generated by Django 3.1.6 on 2021-02-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('player', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('species', models.CharField(max_length=100)),
                ('gravity', models.CharField(max_length=10)),
                ('sex', models.CharField(max_length=2)),
                ('heignt', models.DecimalField(decimal_places=2, default=1.75, max_digits=4)),
                ('weight', models.IntegerField(default=75)),
                ('planet', models.CharField(max_length=80)),
                ('schooling', models.CharField(max_length=20)),
                ('occupation', models.CharField(max_length=22)),
                ('age', models.IntegerField(default=21)),
                ('wealth', models.IntegerField(default=20)),
                ('strength', models.IntegerField(default=2)),
                ('reflex', models.IntegerField(default=2)),
                ('health', models.IntegerField(default=2)),
                ('intuition', models.IntegerField(default=2)),
                ('will', models.IntegerField(default=2)),
                ('presence', models.IntegerField(default=2)),
            ],
        ),
    ]
